[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/pokemons/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

